apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calc-mcp-server.fullname" . }}-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5ob21lLmdscm9sYW5kLmNvbSI6IHsKICAgICAgImF1dGgiOiAiYkd4aGJXRXJiMk53T2xSWFNWQktVVTlNV0ZoWk1VNDNXRUpQV2pKRlZEazJURFpXVlVOUlZEUTRURGhHVWpRNFVrUmFSVU5MT0ZORk9EZE1RVXhLVVZWUFNVNVZNa0UxTXpVPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
